type: "openai"
args:
  api_name: "gpt-4o-2024-05-13"
  api_key: "eyJ0eXAiOiJqd3QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IjIzNzgzNiIsInBhc3N3b3JkIjoiMjM3ODM2MTIzIiwiZXhwIjoyMDMxMzc2MjA0fQ.Lz6IKLMUTWWT5isamrYTmbAcGNFpAqt87YFF2bynP3w"
  api_url: "http://47.88.8.18:8088"
run_args:
  temperature: 0.0