type: "openai"
args:
  api_name: "gpt-4-turbo-2024-04-09"
  api_key: "eyJ0eXAiOiJqd3QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IjMyNDg4NiIsInBhc3N3b3JkIjoiMzI0ODg2MTIzIiwiZXhwIjoyMDEwNjM1NDYyfQ.b1dTeGwpn4eyWQkB3YyOavhvL765n-6jBqmKqgJyoMQ"
  api_url: "http://47.88.8.18:8088/api/ask"
run_args:
  temperature: 0.0
